import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/user";
import { generateJSON } from "@/lib/ai-provider";
import { generateSingleWordPrompt } from "@/lib/prompts/vocabulary";

const VALID_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];
const MAX_INPUT = 60;

/**
 * Add a single user-supplied word to a saved list. The Spanish translation,
 * example sentence, part of speech and CEFR level are auto-generated by the AI.
 */
export async function POST(req: Request) {
  try {
    const { userId: clerkId } = await auth();
    if (!clerkId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const user = await getCurrentUser();
    if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });

    const body = await req.json();
    const { english, listId, locale = "es" } = body as {
      english?: string;
      listId?: string | null;
      locale?: string;
    };

    const input = (english ?? "").trim();
    if (!input) return NextResponse.json({ error: "Enter a word to add" }, { status: 400 });
    if (input.length > MAX_INPUT) {
      return NextResponse.json({ error: `Too long (max ${MAX_INPUT} characters)` }, { status: 400 });
    }

    // Validate list ownership when provided
    if (listId) {
      const list = await prisma.vocabularyList.findUnique({ where: { id: listId } });
      if (!list || list.userId !== user.id) {
        return NextResponse.json({ error: "List not found" }, { status: 404 });
      }
    }

    // If the user already has this exact word, just move it to this list — no AI needed.
    const existing = await prisma.savedWord.findUnique({
      where: { userId_english: { userId: user.id, english: input } },
    });
    if (existing) {
      const moved = await prisma.savedWord.update({
        where: { id: existing.id },
        data: { listId: listId ?? null },
      });
      return NextResponse.json({ word: serialize(moved), alreadyExisted: true });
    }

    // Enrich with AI
    const data = await generateJSON(generateSingleWordPrompt(input, locale), { temperature: 0.4 });
    const enEnglish = typeof data?.english === "string" && data.english.trim() ? data.english.trim() : input;
    const translation = typeof data?.translation === "string" ? data.translation.trim() : "";
    const example = typeof data?.example === "string" ? data.example.trim() : "";
    const partOfSpeech = typeof data?.partOfSpeech === "string" ? data.partOfSpeech.trim() : null;
    const level = VALID_LEVELS.includes(data?.level) ? data.level : "B1";

    if (!translation || !example) {
      return NextResponse.json({ error: "Couldn't generate this word. Try again." }, { status: 503 });
    }

    // The AI may have normalised the spelling to one already saved — upsert on that.
    const word = await prisma.savedWord.upsert({
      where: { userId_english: { userId: user.id, english: enEnglish } },
      create: {
        userId: user.id,
        english: enEnglish,
        spanish: translation,
        example,
        partOfSpeech,
        level,
        listId: listId ?? null,
      },
      update: { listId: listId ?? null },
    });

    return NextResponse.json({ word: serialize(word) });
  } catch (err) {
    console.error("Vocabulary add error:", err);
    return NextResponse.json({ error: "Failed to add word" }, { status: 500 });
  }
}

function serialize(w: {
  id: string; english: string; spanish: string; example: string;
  partOfSpeech: string | null; level: string; notes: string | null;
  listId: string | null; createdAt: Date;
}) {
  return {
    id: w.id,
    english: w.english,
    spanish: w.spanish,
    example: w.example,
    partOfSpeech: w.partOfSpeech,
    level: w.level,
    notes: w.notes,
    listId: w.listId,
    createdAt: w.createdAt.toISOString(),
  };
}
